base: &base
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  <% if ENV['DB_SOCKET'] %>
  socket: <%= ENV['DB_SOCKET'] %>
  <% else %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  <% end %>

production:
  <<: *base

development:
  <<: *base

test: &test
  <<: *base
  database: <%= ENV['RDS_DB_NAME'] %>_test
  
